# Generated by Django 4.2.4 on 2023-12-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_alter_expertises_expertise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='expertises',
            field=models.ManyToManyField(to='painting.expertises'),
        ),
    ]
