# Generated by Django 4.2.4 on 2023-12-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0003_requests_expertises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='request_status',
            new_name='req_status',
        ),
    ]
